development:
  adapter: postgresql
  encoding: unicode
  database: farmstays_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: farmstays_test
  pool: 5
  username: postgres
  password: 
