# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f06372aed171fb072c176959f23b64acd3f53b5af868ec1cf1d89b7813017337e9ebccb9848ca588a28e2cb80c8da45568f01952aa7cc41bc8a9d5ca77edc138

test:
  secret_key_base: f0f213db826dcd457df324bda03c04dff6690e06371bd65de17e335a66973208fbdc66e1181a0127fc6b71128bf646c122d39876893e6d39fd49a82f5ee7c289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
